from PyQt5.QtCore import Qt, QTime, QTimer
from PyQt5.QtGui import QFont
from PyQt5.QtWidgets import QApplication, QLineEdit, QLabel, QPushButton, QWidget,QVBoxLayout,QHBoxLayout
# app = QApplication([])
from final_win import FinalWin
#main_win = QWidget()
#main_win.setWindowTitle('Здоровье')
#main_win.move(900,70)
#main_win.resize(600,500)
#hline = QHBoxLayout()
#v1line = QVBoxLayout()
#v2line = QVBoxLayout()
#text1 = QLabel('Введите ФИО:')
#text2 = QLabel('Полных лет:')
#text3 = QLabel('Лягте на спину и замерьте пульс на 15 секунд. Нажмите кнопку "Начать тест", чтобы запустить таймер.\nРезультат запишите в соответствующее поле')
#text4  = QLabel('Выполните 30 приседаний за 45 секунд. Для этого нажмите кнопку "Начать приседания",\nчтобы запустить счетчик приседаний')
#text5 = QLabel('Лягте на спину и замерьте пульс сначала за первые 15 секунд минуты, затем за последние 15 секунд.\nНажмите кнопку "Начать финальный тест", чтобы запустить таймер.\nЗеленым обозначены секунды, в течение которых необходимо\nпроводить измерения, черным - минуты без замера пульсаций. Результаты запишите в соответствующие поля.')
#time = QLabel('00:00:15')
#button1 = QPushButton('Начать тест')
#button2 = QPushButton('Начать приседания')
#button3 = QPushButton('Начать финальный тест')
#button4 = QPushButton('Отправить результаты')
#vvod1 = QLineEdit()
#vvod2 = QLineEdit()
#vvod3 = QLineEdit()
#vvod4 = QLineEdit()
#vvod5 = QLineEdit()
#v1line.addWidget(text1, alignment = Qt.AlignLeft)
#v1line.addWidget(vvod1, alignment = Qt.AlignLeft)
#v1line.addWidget(text2, alignment = Qt.AlignLeft)
#v1line.addWidget(vvod2, alignment = Qt.AlignLeft)
#v1line.addWidget(text3, alignment = Qt.AlignLeft)
#v1line.addWidget(button1, alignment = Qt.AlignLeft)
#v1line.addWidget(vvod3, alignment = Qt.AlignLeft)
#v1line.addWidget(text4, alignment = Qt.AlignLeft)
#v1line.addWidget(button2, alignment = Qt.AlignLeft)
#v1line.addWidget(text5, alignment = Qt.AlignLeft)
#v1line.addWidget(button3, alignment = Qt.AlignLeft)
#v1line.addWidget(vvod4, alignment = Qt.AlignLeft)
#v1line.addWidget(vvod5, alignment = Qt.AlignLeft)
#v1line.addWidget(button4, alignment = Qt.AlignCenter)
#v2line.addWidget(time, alignment = Qt.AlignLeft)
#main_win.setLayout(hline)
#hline.addLayout(v1line)
#hline.addLayout(v2line)
#main_win.show()
class SecondWin(QWidget):
    def __init__(self):
        super().__init__()
        self.set_appear()
        self.setUI()
        self.connects()
        self.show()
    def set_appear(self):
        self.setWindowTitle('Здоровье')
        # self.move(900,70)
        self.resize(600,500)
    def setUI(self):
        self.hline = QHBoxLayout()
        self.v1line = QVBoxLayout()
        self.v2line = QVBoxLayout()
        self.text1 = QLabel('Введите ФИО:')
        self.text2 = QLabel('Полных лет:')
        self.text3 = QLabel('Лягте на спину и замерьте пульс на 15 секунд. Нажмите кнопку "Начать тест", чтобы запустить таймер.\nРезультат запишите в соответствующее поле')
        self.text4  = QLabel('Выполните 30 приседаний за 45 секунд. Для этого нажмите кнопку "Начать приседания",\nчтобы запустить счетчик приседаний')
        self.text5 = QLabel('Лягте на спину и замерьте пульс сначала за первые 15 секунд минуты, затем за последние 15 секунд.\nНажмите кнопку "Начать финальный тест", чтобы запустить таймер.\nЗеленым обозначены секунды, в течение которых необходимо\nпроводить измерения, черным - минуты без замера пульсаций. Результаты запишите в соответствующие поля.')
        self.time_text = QLabel('00:00:15')
        self.button1 = QPushButton('Начать тест')
        self.button2 = QPushButton('Начать приседания')
        self.button3 = QPushButton('Начать финальный тест')
        self.button4 = QPushButton('Отправить результаты')
        self.vvod1 = QLineEdit()
        self.vvod2 = QLineEdit()
        self.vvod3 = QLineEdit()
        self.vvod4 = QLineEdit()
        self.vvod5 = QLineEdit()
        self.v1line.addWidget(self.text1, alignment = Qt.AlignLeft)
        self.v1line.addWidget(self.vvod1, alignment = Qt.AlignLeft)
        self.v1line.addWidget(self.text2, alignment = Qt.AlignLeft)
        self.v1line.addWidget(self.vvod2, alignment = Qt.AlignLeft)
        self.v1line.addWidget(self.text3, alignment = Qt.AlignLeft)
        self.v1line.addWidget(self.button1, alignment = Qt.AlignLeft)
        self.v1line.addWidget(self.vvod3, alignment = Qt.AlignLeft)
        self.v1line.addWidget(self.text4, alignment = Qt.AlignLeft)
        self.v1line.addWidget(self.button2, alignment = Qt.AlignLeft)
        self.v1line.addWidget(self.text5, alignment = Qt.AlignLeft)
        self.v1line.addWidget(self.button3, alignment = Qt.AlignLeft)
        self.v1line.addWidget(self.vvod4, alignment = Qt.AlignLeft)
        self.v1line.addWidget(self.vvod5, alignment = Qt.AlignLeft)
        self.v1line.addWidget(self.button4, alignment = Qt.AlignCenter)
        self.v2line.addWidget(self.time_text, alignment = Qt.AlignLeft)
        self.setLayout(self.hline)
        self.hline.addLayout(self.v1line)
        self.hline.addLayout(self.v2line)
    def connects(self):
        self.button1.clicked.connect(self.timer1Event)
        self.button2.clicked.connect(self.timer2Event)
        self.button3.clicked.connect(self.timer3Event)
        self.button4.clicked.connect(self.button_click)
    def button_click(self):
        self.hide()
        self.final_win = FinalWin()
    def timer1Event(self):
        global time
        time = QTime(0,1,0)
        self.timer = QTimer()
        time = time.addSecs(-1)
        self.time_text.setText(time.toString('hh:mm:ss'))
        self.time_text.setFont(QFont('Times',36,QFont.Bold))
        self.time_text.setStyleSheet('color: rgb(0,0,0)')
        self.timer.start(1000)
        if time.toString("hh:mm:ss") == "00:00:00":
            self.timer.stop()

    def timer2Event(self):
        global time
        time = QTime(0,0,30)
        self.timer = QTimer()
        time = time.addSecs(-1)
        self.time_text.setText(time.toString('hh:mm:ss')[6:8])
        self.time_text.setFont(QFont('Times',36,QFont.Bold))
        self.time_text.setStyleSheet('color: rgb(0,0,0)')
        self.timer.start(1500)
        if time.toString("hh:mm:ss") == "00:00:00":
            self.timer.stop()
    
    def timer3Event(self):
        global time
        time = QTime(0,1,0)
        self.timer = QTimer()
        time = time.addSecs(-1)
        self.time_text.setText(time.toString('hh:mm:ss')[6:8])
        self.time_text.setFont(QFont('Times',36,QFont.Bold))
        self.timer.start(1000)
        if int(time.toString("hh:mm:ss"[6:8])) >= 45:
            self.time_text.setStyleSheet('color: rgb(0,255,0)')
        elif int(time.toString("hh:mm:ss"[6:8])) <= 15:
            self.time_text.setStyleSheet('color: rgb(0,255,0)')
        else:
            self.time_text.setStyleSheet('color: rgb(0,0,0)')
        


# SecondWin()
# app.exec_()