from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QApplication, QLabel, QPushButton, QWidget,QVBoxLayout,QHBoxLayout, QLineEdit
app = QApplication([])
main_win = QWidget()
main_win.setWindowTitle('Здоровье')
main_win.move(900,70)
main_win.resize(600,500)
hline = QHBoxLayout()
v1line = QVBoxLayout()
v2line = QVBoxLayout()
text1 = QLabel('Введите ФИО:')
text2 = QLabel('Полных лет:')
text3 = QLabel('Лягте на спину и замерьте пульс на 15 секунд. Нажмите кнопку "Начать тест", чтобы запустить таймер.\nРезультат запишите в соответствующее поле')
text4  = QLabel('Выполните 30 приседаний за 45 секунд. Для этого нажмите кнопку "Начать приседания",\nчтобы запустить счетчик приседаний')
text5 = QLabel('Лягте на спину и замерьте пульс сначала за первые 15 секунд минуты, затем за последние 15 секунд.\nНажмите кнопку "Начать финальный тест", чтобы запустить таймер.\nЗеленым обозначены секунды, в течение которых необходимо\nпроводить измерения, черным - минуты без замера пульсаций. Результаты запишите в соответствующие поля.')
button1 = QPushButton('Начать тест')
button2 = QPushButton('Начать приседания')
button3 = QPushButton('Начать финальный тест')
button4 = QPushButton('Отправить результаты')
count1 = QLineEdit()
count2 = QLineEdit()
count3 = QLineEdit()
count4 = QLineEdit()
vline.addWidget(text1, alignment = Qt.AlignCenter)
vline.addWidget(text2, alignment = Qt.AlignCenter)
vline.addWidget(text3, alignment = Qt.AlignCenter)
vline.addWidget(text4, alignment = Qt.AlignCenter)
vline.addWidget(text5, alignment = Qt.AlignCenter)
vline.addWidget(button1, alignment = Qt.AlignCenter)
vline.addWidget(button2, alignment = Qt.AlignCenter)
vline.addWidget(button3, alignment = Qt.AlignCenter)
hline.addWidget(button4, alignment = Qt.AlignCenter)
main_win.setLayout(hline)
hline.addLayout(v1line)
hline.addLayout(v2line)